### ISSUE TITLE
Cannot find module 'hexo/lib/plugins/console/generate'

### ISSUE THREAD

**Issue by uiolee** [jiangtj-lab/hexo-next-pwa#95]
when i run `hexo g`,
it occurs error.

```log
Error: Cannot find module 'hexo/lib/plugins/console/generate'
Require stack:
- E:\git\hexo-website\node_modules\@jiangtj\hexo-next-pwa\lib\service-worker.js
- E:\git\hexo-website\node_modules\@jiangtj\hexo-next-pwa\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Hexo.<anonymous> (E:\git\hexo-website\node_modules\@jiangtj\hexo-next-pwa\lib\service-worker.js:59:29)
    at Hexo.tryCatcher (E:\git\hexo-website\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\git\hexo-website\node_modules\bluebird\js\release\method.js:15:34)
    at Hexo.call (E:\git\hexo-website\node_modules\hexo\dist\hexo\index.js:208:28)
    at E:\git\hexo-website\node_modules\hexo-cli\dist\hexo.js:56:21
    at tryCatcher (E:\git\hexo-website\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\git\hexo-website\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\git\hexo-website\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\git\hexo-website\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\git\hexo-website\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\git\hexo-website\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\git\hexo-website\node_modules\bluebird\js\release\async.js:86:9)
```

hexo 7.0.0-rc1

when i check `node_modules\hexo`, could not get a directory `lib`.
but find `dist`.

**Comment by jiangtj** [comment]
fixed in v4.0.0
